package repository

import "layover-backend/pkg/model"

var Destinations = []model.Destination{
	{
		ID:          "1",
		Name:        "Bali",
		Country:     "Indonesia",
		Description: "A tropical paradise with stunning temples, lush rice terraces, and world-class surf beaches. Perfect for spiritual seekers and adventure lovers.",
		Image:       "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
		Rating:      4.8,
		Reviews:     12450,
		PriceLevel:  2,
		Seasons:     []string{"summer", "spring"},
		Activities:  []string{"Surfing", "Temple Tours", "Rice Terrace Hike", "Yoga Retreat", "Cooking Class"},
		Weather:     "tropical",
		AvgTemp:     28,
		Tags:        []string{"beach", "culture", "spiritual", "adventure"},
		Continent:   "Asia",
	},
	{
		ID:          "2",
		Name:        "Paris",
		Country:     "France",
		Description: "The city of lights — iconic Eiffel Tower, world-class museums, romantic streets, and the finest cuisine on earth.",
		Image:       "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
		Rating:      4.7,
		Reviews:     28900,
		PriceLevel:  4,
		Seasons:     []string{"spring", "summer", "fall"},
		Activities:  []string{"Eiffel Tower", "Louvre Museum", "Seine River Cruise", "Wine Tasting", "Fashion Shopping"},
		Weather:     "temperate",
		AvgTemp:     14,
		Tags:        []string{"romantic", "culture", "food", "fashion", "art"},
		Continent:   "Europe",
	},
	{
		ID:          "3",
		Name:        "Tokyo",
		Country:     "Japan",
		Description: "A dazzling blend of ultramodern and traditional — neon-lit skyscrapers beside ancient temples, sushi bars and anime culture.",
		Image:       "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
		Rating:      4.9,
		Reviews:     19800,
		PriceLevel:  3,
		Seasons:     []string{"spring", "fall"},
		Activities:  []string{"Shibuya Crossing", "Mount Fuji", "Tsukiji Market", "Akihabara", "Tea Ceremony"},
		Weather:     "temperate",
		AvgTemp:     16,
		Tags:        []string{"culture", "food", "technology", "anime", "nature"},
		Continent:   "Asia",
	},
	{
		ID:          "4",
		Name:        "Santorini",
		Country:     "Greece",
		Description: "Breathtaking white-washed buildings perched on volcanic cliffs above the azure Aegean Sea. The ultimate Mediterranean escape.",
		Image:       "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
		Rating:      4.8,
		Reviews:     15600,
		PriceLevel:  4,
		Seasons:     []string{"summer", "spring"},
		Activities:  []string{"Sunset at Oia", "Volcano Hike", "Wine Tasting", "Sailing", "Black Sand Beach"},
		Weather:     "mediterranean",
		AvgTemp:     24,
		Tags:        []string{"romantic", "beach", "photography", "luxury"},
		Continent:   "Europe",
	},
	{
		ID:          "5",
		Name:        "New York",
		Country:     "USA",
		Description: "The city that never sleeps — iconic skyline, world-class Broadway shows, diverse neighborhoods and endless energy.",
		Image:       "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
		Rating:      4.6,
		Reviews:     31200,
		PriceLevel:  4,
		Seasons:     []string{"spring", "summer", "fall", "winter"},
		Activities:  []string{"Central Park", "Times Square", "Broadway Show", "Brooklyn Bridge", "MoMA"},
		Weather:     "temperate",
		AvgTemp:     13,
		Tags:        []string{"urban", "culture", "food", "nightlife", "shopping"},
		Continent:   "North America",
	},
	{
		ID:          "6",
		Name:        "Maldives",
		Country:     "Maldives",
		Description: "Crystal-clear turquoise waters, overwater bungalows, and vibrant coral reefs. The ultimate luxury beach destination.",
		Image:       "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
		Rating:      4.9,
		Reviews:     8900,
		PriceLevel:  4,
		Seasons:     []string{"winter", "spring"},
		Activities:  []string{"Snorkeling", "Scuba Diving", "Overwater Villa", "Dolphin Watching", "Water Sports"},
		Weather:     "tropical",
		AvgTemp:     30,
		Tags:        []string{"luxury", "beach", "diving", "honeymoon", "relaxation"},
		Continent:   "Asia",
	},
	{
		ID:          "7",
		Name:        "Barcelona",
		Country:     "Spain",
		Description: "Gaudi's architectural masterpieces, vibrant nightlife, stunning beaches, and the best tapas you'll ever taste.",
		Image:       "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
		Rating:      4.7,
		Reviews:     22300,
		PriceLevel:  3,
		Seasons:     []string{"spring", "summer", "fall"},
		Activities:  []string{"Sagrada Familia", "Park Güell", "La Rambla", "Gothic Quarter", "Beach Clubs"},
		Weather:     "mediterranean",
		AvgTemp:     18,
		Tags:        []string{"architecture", "beach", "nightlife", "food", "art"},
		Continent:   "Europe",
	},
	{
		ID:          "8",
		Name:        "Cape Town",
		Country:     "South Africa",
		Description: "Where mountains meet the ocean — Table Mountain, penguin colonies, world-class wineries, and diverse cultures.",
		Image:       "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
		Rating:      4.7,
		Reviews:     11200,
		PriceLevel:  2,
		Seasons:     []string{"summer", "spring"},
		Activities:  []string{"Table Mountain", "Cape of Good Hope", "Boulders Beach Penguins", "Wine Tours", "Robben Island"},
		Weather:     "mediterranean",
		AvgTemp:     17,
		Tags:        []string{"nature", "adventure", "wildlife", "culture", "wine"},
		Continent:   "Africa",
	},
	{
		ID:          "9",
		Name:        "Dubai",
		Country:     "UAE",
		Description: "A futuristic city of superlatives — world's tallest building, largest malls, and luxury experiences beyond imagination.",
		Image:       "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
		Rating:      4.6,
		Reviews:     18700,
		PriceLevel:  4,
		Seasons:     []string{"winter", "spring"},
		Activities:  []string{"Burj Khalifa", "Desert Safari", "Dubai Mall", "Palm Jumeirah", "Gold Souk"},
		Weather:     "desert",
		AvgTemp:     28,
		Tags:        []string{"luxury", "shopping", "modern", "desert", "architecture"},
		Continent:   "Asia",
	},
	{
		ID:          "10",
		Name:        "Reykjavik",
		Country:     "Iceland",
		Description: "Chase the Northern Lights, soak in natural hot springs, and explore dramatic volcanic landscapes unlike anywhere on Earth.",
		Image:       "https://images.unsplash.com/photo-1520769945061-0a448c463865?w=800&q=80",
		Rating:      4.8,
		Reviews:     7600,
		PriceLevel:  4,
		Seasons:     []string{"winter", "fall"},
		Activities:  []string{"Northern Lights", "Blue Lagoon", "Golden Circle", "Glacier Hike", "Whale Watching"},
		Weather:     "arctic",
		AvgTemp:     4,
		Tags:        []string{"northern lights", "nature", "adventure", "unique", "photography"},
		Continent:   "Europe",
	},
	{
		ID:          "11",
		Name:        "Kyoto",
		Country:     "Japan",
		Description: "Ancient temples, traditional tea houses, geisha districts, and spectacular cherry blossoms — Japan's cultural heart.",
		Image:       "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
		Rating:      4.9,
		Reviews:     16400,
		PriceLevel:  2,
		Seasons:     []string{"spring", "fall"},
		Activities:  []string{"Fushimi Inari Shrine", "Arashiyama Bamboo Grove", "Geisha Show", "Tea Ceremony", "Nijo Castle"},
		Weather:     "temperate",
		AvgTemp:     15,
		Tags:        []string{"culture", "temples", "nature", "tradition", "photography"},
		Continent:   "Asia",
	},
	{
		ID:          "12",
		Name:        "Machu Picchu",
		Country:     "Peru",
		Description: "The lost city of the Incas perched high in the Andes — one of the most breathtaking archaeological sites on the planet.",
		Image:       "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
		Rating:      4.9,
		Reviews:     9800,
		PriceLevel:  2,
		Seasons:     []string{"spring", "summer"},
		Activities:  []string{"Inca Trail Hike", "Sun Gate", "Huayna Picchu", "Llama Spotting", "Aguas Calientes"},
		Weather:     "temperate",
		AvgTemp:     12,
		Tags:        []string{"history", "adventure", "hiking", "archaeology", "UNESCO"},
		Continent:   "South America",
	},
	{
		ID:          "13",
		Name:        "Amsterdam",
		Country:     "Netherlands",
		Description: "Charming canals, world-class museums, cycling culture, tulip fields, and a vibrant multicultural atmosphere.",
		Image:       "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
		Rating:      4.6,
		Reviews:     21500,
		PriceLevel:  3,
		Seasons:     []string{"spring", "summer"},
		Activities:  []string{"Anne Frank House", "Van Gogh Museum", "Canal Cruise", "Keukenhof Gardens", "Cycling Tour"},
		Weather:     "temperate",
		AvgTemp:     11,
		Tags:        []string{"culture", "art", "cycling", "canals", "history"},
		Continent:   "Europe",
	},
	{
		ID:          "14",
		Name:        "Safari in Kenya",
		Country:     "Kenya",
		Description: "Witness the Great Migration, spot the Big Five, and experience the raw beauty of the African savannah at golden hour.",
		Image:       "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
		Rating:      4.9,
		Reviews:     6300,
		PriceLevel:  3,
		Seasons:     []string{"summer", "winter"},
		Activities:  []string{"Game Drive", "Great Migration", "Hot Air Balloon", "Maasai Village", "Bush Dinner"},
		Weather:     "tropical",
		AvgTemp:     22,
		Tags:        []string{"wildlife", "safari", "nature", "adventure", "photography"},
		Continent:   "Africa",
	},
	{
		ID:          "15",
		Name:        "Amalfi Coast",
		Country:     "Italy",
		Description: "Dramatic cliffside villages cascading down to turquoise waters, fresh seafood, and the most scenic coastal drive in Europe.",
		Image:       "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
		Rating:      4.8,
		Reviews:     13700,
		PriceLevel:  4,
		Seasons:     []string{"spring", "summer"},
		Activities:  []string{"Positano Walk", "Boat Tour", "Limoncello Tasting", "Hiking Path of Gods", "Ravello Villa"},
		Weather:     "mediterranean",
		AvgTemp:     22,
		Tags:        []string{"scenic", "romantic", "food", "coastal", "photography"},
		Continent:   "Europe",
	},
	{
		ID:          "16",
		Name:        "Queenstown",
		Country:     "New Zealand",
		Description: "The adventure capital of the world — bungee jumping, skydiving, skiing, and stunning fjord landscapes.",
		Image:       "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
		Rating:      4.8,
		Reviews:     8900,
		PriceLevel:  3,
		Seasons:     []string{"winter", "summer"},
		Activities:  []string{"Bungee Jumping", "Skiing", "Milford Sound", "Skydiving", "Jet Boat"},
		Weather:     "temperate",
		AvgTemp:     10,
		Tags:        []string{"adventure", "extreme sports", "nature", "skiing", "scenic"},
		Continent:   "Oceania",
	},
	{
		ID:          "17",
		Name:        "Prague",
		Country:     "Czech Republic",
		Description: "A fairy-tale city of medieval castles, Gothic cathedrals, cobblestone streets and the world's best beer culture.",
		Image:       "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80",
		Rating:      4.7,
		Reviews:     17800,
		PriceLevel:  2,
		Seasons:     []string{"spring", "summer", "fall"},
		Activities:  []string{"Prague Castle", "Charles Bridge", "Old Town Square", "Beer Hall", "Bohemian Switzerland"},
		Weather:     "temperate",
		AvgTemp:     10,
		Tags:        []string{"history", "architecture", "nightlife", "budget", "culture"},
		Continent:   "Europe",
	},
	{
		ID:          "18",
		Name:        "Rio de Janeiro",
		Country:     "Brazil",
		Description: "Christ the Redeemer, Copacabana Beach, samba rhythms and a vibrant carnival energy that never stops.",
		Image:       "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800&q=80",
		Rating:      4.5,
		Reviews:     14200,
		PriceLevel:  2,
		Seasons:     []string{"summer", "fall"},
		Activities:  []string{"Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Samba Show", "Favela Tour"},
		Weather:     "tropical",
		AvgTemp:     26,
		Tags:        []string{"beach", "culture", "carnival", "nightlife", "iconic"},
		Continent:   "South America",
	},
	{
		ID:          "19",
		Name:        "Marrakech",
		Country:     "Morocco",
		Description: "A sensory explosion of spice-scented souks, ornate palaces, rooftop riads and the vibrant Djemaa el-Fna square.",
		Image:       "https://images.unsplash.com/photo-1597212720158-f5e0f998dc35?w=800&q=80",
		Rating:      4.6,
		Reviews:     10500,
		PriceLevel:  1,
		Seasons:     []string{"spring", "fall", "winter"},
		Activities:  []string{"Medina Souk", "Majorelle Garden", "Sahara Desert Tour", "Hammam Spa", "Cooking Class"},
		Weather:     "desert",
		AvgTemp:     20,
		Tags:        []string{"culture", "exotic", "food", "shopping", "desert"},
		Continent:   "Africa",
	},
	{
		ID:          "20",
		Name:        "Sydney",
		Country:     "Australia",
		Description: "Iconic Opera House, Harbour Bridge, Bondi Beach and a laid-back outdoor culture under year-round sunshine.",
		Image:       "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
		Rating:      4.7,
		Reviews:     19100,
		PriceLevel:  3,
		Seasons:     []string{"summer", "spring", "fall"},
		Activities:  []string{"Opera House Tour", "Bondi Beach", "Harbour Bridge Climb", "Blue Mountains", "Wildlife Park"},
		Weather:     "temperate",
		AvgTemp:     18,
		Tags:        []string{"beach", "culture", "outdoor", "wildlife", "iconic"},
		Continent:   "Oceania",
	},
}

var MockWeather = map[string]model.WeatherData{
	"bali": {
		City: "Bali", Country: "Indonesia", Temperature: 30, FeelsLike: 34,
		Humidity: 78, WindSpeed: 12, Condition: "Partly Cloudy", Icon: "⛅", UVIndex: 8,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 31, Low: 24, Icon: "☀️", Condition: "Sunny"},
			{Day: "Tue", High: 29, Low: 23, Icon: "⛅", Condition: "Partly Cloudy"},
			{Day: "Wed", High: 27, Low: 22, Icon: "🌧️", Condition: "Rainy"},
			{Day: "Thu", High: 30, Low: 24, Icon: "☀️", Condition: "Sunny"},
			{Day: "Fri", High: 31, Low: 25, Icon: "☀️", Condition: "Sunny"},
		},
	},
	"paris": {
		City: "Paris", Country: "France", Temperature: 16, FeelsLike: 14,
		Humidity: 65, WindSpeed: 18, Condition: "Overcast", Icon: "☁️", UVIndex: 4,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 17, Low: 10, Icon: "⛅", Condition: "Partly Cloudy"},
			{Day: "Tue", High: 15, Low: 9, Icon: "🌧️", Condition: "Light Rain"},
			{Day: "Wed", High: 14, Low: 8, Icon: "🌧️", Condition: "Rainy"},
			{Day: "Thu", High: 18, Low: 11, Icon: "☀️", Condition: "Sunny"},
			{Day: "Fri", High: 19, Low: 12, Icon: "☀️", Condition: "Sunny"},
		},
	},
	"tokyo": {
		City: "Tokyo", Country: "Japan", Temperature: 22, FeelsLike: 21,
		Humidity: 55, WindSpeed: 10, Condition: "Clear", Icon: "☀️", UVIndex: 6,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 23, Low: 15, Icon: "☀️", Condition: "Sunny"},
			{Day: "Tue", High: 21, Low: 14, Icon: "⛅", Condition: "Partly Cloudy"},
			{Day: "Wed", High: 20, Low: 13, Icon: "🌧️", Condition: "Rainy"},
			{Day: "Thu", High: 22, Low: 15, Icon: "⛅", Condition: "Partly Cloudy"},
			{Day: "Fri", High: 24, Low: 16, Icon: "☀️", Condition: "Sunny"},
		},
	},
	"dubai": {
		City: "Dubai", Country: "UAE", Temperature: 35, FeelsLike: 40,
		Humidity: 45, WindSpeed: 15, Condition: "Hot & Sunny", Icon: "☀️", UVIndex: 11,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 36, Low: 26, Icon: "☀️", Condition: "Sunny"},
			{Day: "Tue", High: 37, Low: 27, Icon: "☀️", Condition: "Hot"},
			{Day: "Wed", High: 35, Low: 25, Icon: "🌬️", Condition: "Windy"},
			{Day: "Thu", High: 34, Low: 25, Icon: "☀️", Condition: "Sunny"},
			{Day: "Fri", High: 36, Low: 26, Icon: "☀️", Condition: "Sunny"},
		},
	},
	"reykjavik": {
		City: "Reykjavik", Country: "Iceland", Temperature: 3, FeelsLike: -1,
		Humidity: 82, WindSpeed: 30, Condition: "Snowy", Icon: "❄️", UVIndex: 1,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 4, Low: -2, Icon: "❄️", Condition: "Snow"},
			{Day: "Tue", High: 2, Low: -4, Icon: "🌨️", Condition: "Heavy Snow"},
			{Day: "Wed", High: 5, Low: -1, Icon: "🌫️", Condition: "Foggy"},
			{Day: "Thu", High: 3, Low: -2, Icon: "❄️", Condition: "Snow"},
			{Day: "Fri", High: 6, Low: 0, Icon: "⛅", Condition: "Partly Cloudy"},
		},
	},
	"default": {
		City: "Unknown", Country: "", Temperature: 20, FeelsLike: 18,
		Humidity: 60, WindSpeed: 14, Condition: "Clear", Icon: "☀️", UVIndex: 5,
		Forecast: []model.Forecast{
			{Day: "Mon", High: 22, Low: 14, Icon: "☀️", Condition: "Sunny"},
			{Day: "Tue", High: 21, Low: 13, Icon: "⛅", Condition: "Partly Cloudy"},
			{Day: "Wed", High: 19, Low: 12, Icon: "🌧️", Condition: "Light Rain"},
			{Day: "Thu", High: 22, Low: 14, Icon: "☀️", Condition: "Sunny"},
			{Day: "Fri", High: 23, Low: 15, Icon: "☀️", Condition: "Sunny"},
		},
	},
}

var MockTrips = []model.Trip{
	{
		ID: "t1", Name: "Bali Adventure", Destination: "Bali, Indonesia",
		Image:      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
		StartDate:  "2026-05-10", EndDate: "2026-05-17",
		Budget: 2000, TotalSpent: 1450, Status: "upcoming",
		Members: []model.Member{
			{ID: "u1", Name: "Alex", Avatar: "A", Paid: 500},
			{ID: "u2", Name: "Sam", Avatar: "S", Paid: 500},
			{ID: "u3", Name: "Jordan", Avatar: "J", Paid: 450},
		},
		Itinerary: []model.DayPlan{
			{Day: 1, Date: "2026-05-10", Activities: []model.Activity{
				{Time: "09:00", Name: "Check-in Ubud Villa", Type: "accommodation", Cost: 120, Duration: "30 min", Rating: 4.8, Description: "Stunning jungle villa with private pool", Address: "Ubud, Bali"},
				{Time: "13:00", Name: "Tegalalang Rice Terrace", Type: "attraction", Cost: 5, Duration: "2 hrs", Rating: 4.7, Description: "Iconic Bali rice terraces with swing", Address: "Tegalalang, Ubud"},
				{Time: "19:00", Name: "Locavore Restaurant", Type: "food", Cost: 45, Duration: "2 hrs", Rating: 4.9, Description: "Award-winning modern Balinese cuisine", Address: "Jl. Dewi Sita, Ubud"},
			}},
			{Day: 2, Date: "2026-05-11", Activities: []model.Activity{
				{Time: "06:00", Name: "Sunrise at Mount Batur", Type: "attraction", Cost: 35, Duration: "5 hrs", Rating: 4.9, Description: "Volcanic sunrise hike with guide", Address: "Kintamani, Bali"},
				{Time: "15:00", Name: "Tanah Lot Temple", Type: "attraction", Cost: 5, Duration: "2 hrs", Rating: 4.6, Description: "Iconic sea temple at sunset", Address: "Tabanan, Bali"},
				{Time: "20:00", Name: "Jimbaran Seafood BBQ", Type: "food", Cost: 30, Duration: "2 hrs", Rating: 4.7, Description: "Fresh seafood on the beach", Address: "Jimbaran Bay, Bali"},
			}},
			{Day: 3, Date: "2026-05-12", Activities: []model.Activity{
				{Time: "10:00", Name: "Seminyak Beach Club", Type: "attraction", Cost: 20, Duration: "4 hrs", Rating: 4.5, Description: "Relax at Bali's trendiest beach club", Address: "Seminyak, Bali"},
				{Time: "19:30", Name: "Ku De Ta Sunset Dinner", Type: "food", Cost: 55, Duration: "2.5 hrs", Rating: 4.8, Description: "Iconic beachfront dinner with live DJ", Address: "Seminyak Beach, Bali"},
			}},
		},
	},
	{
		ID: "t2", Name: "Japan Spring Tour", Destination: "Kyoto, Japan",
		Image:      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
		StartDate:  "2026-04-01", EndDate: "2026-04-08",
		Budget: 3500, TotalSpent: 2100, Status: "upcoming",
		Members: []model.Member{
			{ID: "u1", Name: "Alex", Avatar: "A", Paid: 1050},
			{ID: "u4", Name: "Maya", Avatar: "M", Paid: 1050},
		},
		Itinerary: []model.DayPlan{
			{Day: 1, Date: "2026-04-01", Activities: []model.Activity{
				{Time: "14:00", Name: "Check-in Ryokan", Type: "accommodation", Cost: 180, Duration: "1 hr", Rating: 4.9, Description: "Traditional Japanese inn with onsen", Address: "Higashiyama, Kyoto"},
				{Time: "17:00", Name: "Fushimi Inari Shrine", Type: "attraction", Cost: 0, Duration: "2 hrs", Rating: 4.9, Description: "Walk through thousands of torii gates at dusk", Address: "Fushimi-ku, Kyoto"},
				{Time: "20:00", Name: "Nishiki Market dinner", Type: "food", Cost: 35, Duration: "1.5 hrs", Rating: 4.7, Description: "Street food and fresh sashimi at Japan's kitchen", Address: "Nishiki, Kyoto"},
			}},
			{Day: 2, Date: "2026-04-02", Activities: []model.Activity{
				{Time: "08:00", Name: "Arashiyama Bamboo Grove", Type: "attraction", Cost: 0, Duration: "1.5 hrs", Rating: 4.8, Description: "Stunning bamboo forest walk at sunrise", Address: "Arashiyama, Kyoto"},
				{Time: "11:00", Name: "Monkey Park Iwatayama", Type: "attraction", Cost: 6, Duration: "1 hr", Rating: 4.5, Description: "Wild macaque monkeys with panoramic city view", Address: "Arashiyama, Kyoto"},
				{Time: "19:00", Name: "Izakaya Dinner", Type: "food", Cost: 40, Duration: "2 hrs", Rating: 4.8, Description: "Authentic Japanese izakaya with sake", Address: "Gion, Kyoto"},
			}},
		},
	},
	{
		ID: "t3", Name: "Iceland Northern Lights", Destination: "Reykjavik, Iceland",
		Image:      "https://images.unsplash.com/photo-1520769945061-0a448c463865?w=800&q=80",
		StartDate:  "2026-02-14", EndDate: "2026-02-19",
		Budget: 4000, TotalSpent: 3800, Status: "completed",
		Members: []model.Member{
			{ID: "u1", Name: "Alex", Avatar: "A", Paid: 1900},
			{ID: "u5", Name: "Casey", Avatar: "C", Paid: 1900},
		},
		Itinerary: []model.DayPlan{
			{Day: 1, Date: "2026-02-14", Activities: []model.Activity{
				{Time: "12:00", Name: "Check-in Hotel Borg", Type: "accommodation", Cost: 220, Duration: "1 hr", Rating: 4.7, Description: "Art deco hotel in the heart of Reykjavik", Address: "Pósthússtræti 11, Reykjavik"},
				{Time: "14:00", Name: "Golden Circle Tour", Type: "attraction", Cost: 85, Duration: "8 hrs", Rating: 4.9, Description: "Geysir, Gullfoss waterfall & Þingvellir", Address: "Golden Circle, Iceland"},
				{Time: "22:00", Name: "Northern Lights Hunt", Type: "attraction", Cost: 60, Duration: "3 hrs", Rating: 4.8, Description: "Guided aurora borealis tour away from city lights", Address: "Countryside, Iceland"},
			}},
			{Day: 2, Date: "2026-02-15", Activities: []model.Activity{
				{Time: "09:00", Name: "Blue Lagoon", Type: "attraction", Cost: 85, Duration: "3 hrs", Rating: 4.8, Description: "Iconic geothermal spa in a lava field", Address: "Grindavík, Iceland"},
				{Time: "19:00", Name: "Dill Restaurant", Type: "food", Cost: 120, Duration: "2.5 hrs", Rating: 4.9, Description: "Michelin-star New Nordic cuisine", Address: "Hverfisgata 12, Reykjavik"},
			}},
		},
	},
}

var MockOutfits = []model.Outfit{
	// Summer
	{
		ID: "o1", TempRange: "28–38°C", Season: "summer",
		Style: "Tropical Casual", Description: "Ultra-light fabrics for beach days and open-air dining. Maximise airflow, minimise bulk.",
		Items:  []string{"Linen shirt (white or pastel)", "Breathable shorts", "Leather sandals", "Polarised sunglasses", "Wide-brim straw hat", "SPF 50 reef-safe sunscreen", "Lightweight tote bag"},
		Colors: []string{"#FFF3CD", "#87CEEB", "#A8E6CF", "#FFB347"},
	},
	{
		ID: "o2", TempRange: "25–34°C", Season: "summer",
		Style: "Resort Chic", Description: "Elevated poolside and beachside looks that take you from lounging to cocktail hour effortlessly.",
		Items:  []string{"Flowy sundress or linen trousers", "Swimwear underneath", "Espadrilles", "Oversized sunglasses", "Crossbody bag", "Light cover-up or kimono", "Gold jewellery"},
		Colors: []string{"#FFD700", "#FF6B6B", "#4ECDC4", "#FFFFFF"},
	},
	{
		ID: "o3", TempRange: "30–40°C", Season: "summer",
		Style: "Desert Explorer", Description: "Protect yourself from intense heat and sun while staying stylish in arid and desert climates.",
		Items:  []string{"Long-sleeve UV-protection shirt", "Lightweight cargo trousers", "Closed-toe sandals", "Buff/neck gaiter", "Wide brim sun hat", "Hydration pack", "Lightweight sunglasses"},
		Colors: []string{"#DEB887", "#F5DEB3", "#8B7355", "#CD853F"},
	},
	// Spring
	{
		ID: "o4", TempRange: "12–22°C", Season: "spring",
		Style: "European City Stroller", Description: "Versatile layers for unpredictable spring weather. Stylish enough for museums, cafés, and cobbled streets.",
		Items:  []string{"Light trench coat", "Slim chinos or tailored jeans", "White shirt or light knit", "Clean leather sneakers", "Mini crossbody bag", "Silk scarf", "Compact umbrella"},
		Colors: []string{"#B0C4DE", "#F5F5DC", "#8FBC8F", "#D2B48C"},
	},
	{
		ID: "o5", TempRange: "15–24°C", Season: "spring",
		Style: "Cherry Blossom Wanderer", Description: "Soft pastels and light layers perfect for Japan's hanami season or any spring garden tour.",
		Items:  []string{"Pastel blazer or cardigan", "Floral midi dress or chinos", "Comfortable walking shoes", "Tote bag", "Light scarf", "Simple stud earrings"},
		Colors: []string{"#FFB7C5", "#FFF0F5", "#C8A2C8", "#98FB98"},
	},
	// Winter
	{
		ID: "o6", TempRange: "−15–5°C", Season: "winter",
		Style: "Arctic Ready", Description: "Serious cold-weather gear layered for sub-zero adventures. Function meets Scandinavian style.",
		Items:  []string{"Merino wool thermal base layer", "Fleece mid-layer", "Waterproof insulated parka", "Thermal waterproof trousers", "Mukluks or snow boots", "Wool gloves + liner gloves", "Balaclava", "Thermal socks (2 pairs)"},
		Colors: []string{"#2C3E50", "#7F8C8D", "#ECF0F1", "#3498DB"},
	},
	{
		ID: "o7", TempRange: "0–10°C", Season: "winter",
		Style: "Winter Chic", Description: "Cosy and polished for city winters — think layered knitwear, tailored coats, and sleek boots.",
		Items:  []string{"Long wool overcoat", "Cashmere turtleneck", "Dark slim jeans or tailored trousers", "Chelsea or ankle boots", "Leather gloves", "Wool beanie or beret", "Statement scarf"},
		Colors: []string{"#1C1C1C", "#8B7355", "#4A4A4A", "#D4C5A9"},
	},
	{
		ID: "o8", TempRange: "5–12°C", Season: "winter",
		Style: "Ski Lodge Casual", Description: "Après-ski style that's just as good off the mountain — warm, cosy, and casually luxurious.",
		Items:  []string{"Chunky cable-knit sweater", "Ski jacket (packable)", "Insulated ski trousers", "Thermal leggings", "Snow boots", "Pom-pom beanie", "Neck warmer"},
		Colors: []string{"#8B0000", "#FFFAFA", "#228B22", "#4169E1"},
	},
	// Fall
	{
		ID: "o9", TempRange: "10–20°C", Season: "fall",
		Style: "Autumn Classic", Description: "Timeless warm-toned layers — the perfect wardrobe for leaf-peeping, wine tours, and city exploring.",
		Items:  []string{"Camel trench coat", "Dark jeans or tailored trousers", "Lightweight turtleneck or knit", "Ankle boots", "Leather tote bag", "Plaid scarf"},
		Colors: []string{"#8B4513", "#DAA520", "#556B2F", "#CD853F"},
	},
	{
		ID: "o10", TempRange: "8–18°C", Season: "fall",
		Style: "Urban Explorer", Description: "Practical, layered streetwear for exploring cities in cooler autumn weather — rain-ready but still sharp.",
		Items:  []string{"Waxed or quilted jacket", "Hoodie or crewneck sweatshirt", "Straight-leg trousers", "Chunky trainers or boots", "Baseball cap or flat cap", "Backpack", "Light merino beanie"},
		Colors: []string{"#4A5568", "#718096", "#E2E8F0", "#2D3748"},
	},
}